const { PDFDocument, rgb, degrees, StandardFonts } = require('pdf-lib');
const fs = require('fs');
const path = require('path');

const addWatermarkToPDF = async (inputPath, outputPath, text, logoPath) => {
  try {
    const existingPdfBytes = fs.readFileSync(inputPath);
    const pdfDoc = await PDFDocument.load(existingPdfBytes);
    const helveticaFont = await pdfDoc.embedFont(StandardFonts.Helvetica);
    const pages = pdfDoc.getPages();

    for (const page of pages) {
      const { width, height } = page.getSize();

      if (logoPath && fs.existsSync(logoPath)) {
        try {
          const logoBytes = fs.readFileSync(logoPath);
          const ext = path.extname(logoPath).toLowerCase();
          let logoImage;
          if (ext === '.png') {
            logoImage = await pdfDoc.embedPng(logoBytes);
          } else {
            logoImage = await pdfDoc.embedJpg(logoBytes);
          }
          const logoDims = logoImage.scale(0.3);
          page.drawImage(logoImage, {
            x: width / 2 - logoDims.width / 2,
            y: height / 2 - logoDims.height / 2,
            width: logoDims.width,
            height: logoDims.height,
            opacity: 0.08,
          });
        } catch (logoErr) {
          console.warn('Logo watermark error:', logoErr.message);
        }
      }

      const watermarkText = text || 'Generated by FlacronAI — Upgrade to remove watermark';
      const fontSize = 18;

      for (let i = 0; i < 3; i++) {
        page.drawText(watermarkText, {
          x: width * 0.05,
          y: height * (0.25 + i * 0.25),
          size: fontSize,
          font: helveticaFont,
          color: rgb(0.6, 0.6, 0.6),
          opacity: 0.25,
          rotate: degrees(35),
        });
      }
    }

    const pdfBytes = await pdfDoc.save();
    fs.writeFileSync(outputPath, pdfBytes);
    return outputPath;
  } catch (err) {
    console.error('Watermark error:', err);
    throw err;
  }
};

const addCompanyWatermark = async (inputPath, outputPath, companyName, opacity = 0.3) => {
  return addWatermarkToPDF(inputPath, outputPath, `DRAFT — ${companyName}`, null);
};

module.exports = { addWatermarkToPDF, addCompanyWatermark };
