const PDFDocument = require('pdfkit');
const fs = require('fs');

const generatePDF = async (report, options = {}) => {
  return new Promise((resolve, reject) => {
    try {
      const {
        outputPath,
        logoPath,
        companyName = 'FlacronAI',
        primaryColor = [249, 115, 22],
        watermark = false,
        watermarkText = 'Generated by FlacronAI — Upgrade to remove watermark',
        reportFooter = null,
        hideFlacronBranding = false,
      } = options;

      const accentHex = '#' + primaryColor.map(v => Math.round(v).toString(16).padStart(2, '0')).join('');

      const doc = new PDFDocument({
        margins: { top: 62, bottom: 0, left: 50, right: 50 },
        size: 'LETTER',
        autoFirstPage: false,
        bufferPages: true,   // key: buffer all pages for post-processing
        info: {
          Title: `Insurance Inspection Report — ${report.claimNumber || 'N/A'}`,
          Author: companyName,
          Subject: `${report.lossType || ''} — ${report.reportType || ''}`,
          Creator: hideFlacronBranding ? companyName : 'FlacronAI',
        },
      });

      const stream = fs.createWriteStream(outputPath);
      doc.pipe(stream);

      // Ensure every auto-flow page starts content below the header band
      doc.on('pageAdded', () => {
        doc.y = 62;
      });

      const pageWidth   = 612;
      const pageHeight  = 792;
      const margin      = 50;
      const contentWidth = pageWidth - margin * 2;

      // ── helper: add a content page (white body, header/footer added later) ──
      const addPage = () => {
        doc.addPage();
        doc.y = 62; // content starts below the header band (drawn in post-process)
      };

      // ── helper: ensure space on current page ──────────────────────────────
      const ensureSpace = (needed = 80) => {
        if (doc.y > pageHeight - 32 - needed) {
          addPage();
        }
      };

      // ── TABLE state ───────────────────────────────────────────────────────
      let inTable   = false;
      let tableRows = [];

      const flushTable = () => {
        if (tableRows.length === 0) return;
        const cols = tableRows[0].length;
        const colW  = contentWidth / Math.max(cols, 1);
        tableRows.forEach((row, ri) => {
          ensureSpace(28);
          const rowH  = 24;
          const rowY  = doc.y;
          const bg    = ri === 0 ? accentHex : (ri % 2 === 0 ? '#f8fafc' : 'white');
          // Draw row background
          doc.rect(margin, rowY, contentWidth, rowH).fill(bg);
          // Draw cell text with absolute y positioning
          doc.fontSize(9)
            .fillColor(ri === 0 ? 'white' : '#1e293b')
            .font(ri === 0 ? 'Helvetica-Bold' : 'Helvetica');
          row.forEach((cell, ci) => {
            doc.text(
              cell.trim().replace(/\*\*(.*?)\*\*/g, '$1'),
              margin + ci * colW + 4,
              rowY + 7,
              { width: colW - 8, ellipsis: true, lineBreak: false }
            );
          });
          doc.y = rowY + rowH;
        });
        doc.y += 6;
        tableRows = [];
        inTable   = false;
      };

      // ══════════════════════════════════════════════════════════════════════
      // PAGE 1 — COVER
      // ══════════════════════════════════════════════════════════════════════
      doc.addPage();      // manual add; no header/footer yet
      doc.rect(0, 0, pageWidth, pageHeight).fill('#0f172a');
      doc.rect(0, 0, pageWidth, 6).fill(accentHex);

      const cx = pageWidth / 2;

      if (logoPath && fs.existsSync(logoPath)) {
        try { doc.image(logoPath, cx - 55, 90, { width: 110, fit: [110, 70] }); } catch {}
      }

      doc.fontSize(10).fillColor(accentHex).font('Helvetica')
        .text(
          hideFlacronBranding ? companyName.toUpperCase() : 'FLACRONAI',
          0, 185, { width: pageWidth, align: 'center', characterSpacing: 3 }
        );

      doc.fontSize(26).fillColor('white').font('Helvetica-Bold')
        .text('INSURANCE INSPECTION REPORT', margin, 215, { width: contentWidth, align: 'center' });

      doc.rect(cx - 90, 268, 180, 2).fill(accentHex);

      const details = [
        ['Report Type',      report.reportType || 'Initial'],
        ['Claim Number',     report.claimNumber || ''],
        ['Insured Name',     report.insuredName || ''],
        ['Property Address', report.propertyAddress || ''],
        ['Date of Loss',     report.lossDate || ''],
        ['Loss Type',        report.lossType || ''],
        ['Report Date',      new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })],
      ];

      details.forEach(([label, value], i) => {
        const y = 290 + i * 38;
        doc.rect(cx - 175, y, 350, 34).fill('#1e293b');
        doc.fontSize(8).fillColor('#94a3b8').font('Helvetica')
          .text(label.toUpperCase(), cx - 162, y + 5, { width: 324, characterSpacing: 1 });
        doc.fontSize(11).fillColor('white').font('Helvetica-Bold')
          .text(value || '—', cx - 162, y + 17, { width: 324 });
      });

      doc.fontSize(8).fillColor('#475569').font('Helvetica')
        .text(
          `Prepared by ${hideFlacronBranding ? companyName : 'FlacronAI'} AI System`,
          margin, pageHeight - 65, { width: contentWidth, align: 'center' }
        );

      // ══════════════════════════════════════════════════════════════════════
      // PAGE 2 — TABLE OF CONTENTS
      // ══════════════════════════════════════════════════════════════════════
      doc.addPage();
      doc.rect(0, 42, pageWidth, pageHeight - 74).fill('white');

      doc.fontSize(20).fillColor('#0f172a').font('Helvetica-Bold').text('Table of Contents', margin, 72);
      doc.rect(margin, 97, contentWidth, 2).fill(accentHex);

      const tocSections = [
        'Section 1: Report Header',
        'Section 2: Insured Information',
        'Section 3: Property Description',
        'Section 4: Scope of Loss / Cause of Loss',
        'Section 5: Damage Assessment',
        'Section 6: Scope of Work',
        'Section 7: Estimated Loss Summary',
        'Section 8: Supporting Documentation',
        'Section 9: Conclusion / Adjuster Notes',
      ];
      tocSections.forEach((sec, i) => {
        const y = 108 + i * 34;
        doc.rect(margin, y, contentWidth, 30).fill(i % 2 === 0 ? '#f8fafc' : 'white');
        doc.fontSize(10).fillColor('#1e293b').font('Helvetica')
          .text(sec, margin + 12, y + 9, { width: contentWidth - 60 });
        doc.fontSize(9).fillColor('#94a3b8')
          .text(`${i + 3}`, margin + contentWidth - 40, y + 9, { width: 30, align: 'right' });
      });

      // ══════════════════════════════════════════════════════════════════════
      // PAGE 3+ — REPORT CONTENT
      // ══════════════════════════════════════════════════════════════════════
      addPage();
      doc.rect(0, 42, pageWidth, pageHeight - 74).fill('white');

      const content = report.content || '';
      const lines   = content.split('\n');

      for (const line of lines) {
        // H1
        if (line.startsWith('# ')) {
          flushTable();
          ensureSpace(50);
          doc.fontSize(16).fillColor('#0f172a').font('Helvetica-Bold')
            .text(line.slice(2), margin, doc.y + 8, { width: contentWidth });
          doc.rect(margin, doc.y + 2, contentWidth, 1.5).fill(accentHex);
          doc.y += 14;
          continue;
        }

        // H2
        if (line.startsWith('## ')) {
          flushTable();
          ensureSpace(60);
          const title = line.slice(3);
          const h2y = doc.y + 4;
          doc.rect(margin - 5, h2y, contentWidth + 10, 32).fill(accentHex);
          doc.fontSize(12).fillColor('white').font('Helvetica-Bold')
            .text(title, margin + 5, h2y + 10, { width: contentWidth - 10, lineBreak: false });
          doc.y = h2y + 44;
          continue;
        }

        // H3
        if (line.startsWith('### ')) {
          flushTable();
          ensureSpace(40);
          doc.fontSize(11).fillColor('#1e293b').font('Helvetica-Bold')
            .text(line.slice(4), margin, doc.y + 5, { width: contentWidth });
          doc.y += 4;
          continue;
        }

        // Table row
        if (line.startsWith('|')) {
          inTable = true;
          const cells = line.split('|').filter(c => c.trim() && !c.trim().match(/^[-:]+$/));
          if (cells.length > 0) tableRows.push(cells);
          continue;
        }

        // End of table on blank line
        if (inTable && line.trim() === '') {
          flushTable();
          doc.y += 4;
          continue;
        }

        // Flush table on any non-table content
        if (inTable) {
          flushTable();
        }

        // HR
        if (line.trim() === '---') {
          ensureSpace(20);
          doc.rect(margin, doc.y + 6, contentWidth, 1).fill('#e2e8f0');
          doc.y += 16;
          continue;
        }

        // Bullet
        if (line.trim().startsWith('- ') || line.trim().startsWith('* ')) {
          ensureSpace(20);
          const text = '•  ' + line.trim().slice(2).replace(/\*\*(.*?)\*\*/g, '$1');
          doc.fontSize(10).fillColor('#374151').font('Helvetica')
            .text(text, margin + 12, doc.y + 2, { width: contentWidth - 12 });
          continue;
        }

        // Blank line
        if (line.trim() === '') {
          if (doc.y + 5 > pageHeight - 32) addPage();
          else doc.y += 5;
          continue;
        }

        // Regular paragraph
        const clean = line
          .replace(/\*\*(.*?)\*\*/g, '$1')
          .replace(/\*(.*?)\*/g, '$1')
          .replace(/`(.*?)`/g, '$1');
        if (clean.trim()) {
          ensureSpace(20);
          doc.fontSize(10).fillColor('#374151').font('Helvetica')
            .text(clean, margin, doc.y + 2, { width: contentWidth });
        }
      }

      flushTable(); // flush any remaining table

      // ══════════════════════════════════════════════════════════════════════
      // SIGNATURE PAGE
      // ══════════════════════════════════════════════════════════════════════
      addPage();
      doc.rect(0, 42, pageWidth, pageHeight - 74).fill('white');
      doc.y = 72;

      doc.fontSize(18).fillColor('#0f172a').font('Helvetica-Bold').text('Adjuster Certification', margin, 72);
      doc.rect(margin, 96, contentWidth, 2).fill(accentHex);
      doc.y = 114;

      doc.fontSize(10).fillColor('#374151').font('Helvetica')
        .text(
          'I certify that the information contained in this report is accurate and complete to the best of my knowledge.',
          margin, doc.y, { width: contentWidth }
        );

      doc.y += 50;
      [['Adjuster Signature', margin], ['Date', margin + 310]].forEach(([label, x]) => {
        doc.rect(x, doc.y + 36, 210, 1).fill('#374151');
        doc.fontSize(8).fillColor('#94a3b8').text(label, x, doc.y + 42, { width: 210 });
      });

      doc.y += 90;
      ['Adjuster Name (Print)', 'License Number', 'Company / Firm Name'].forEach(label => {
        doc.rect(margin, doc.y + 30, contentWidth, 1).fill('#374151');
        doc.fontSize(8).fillColor('#94a3b8').text(label, margin, doc.y + 36, { width: contentWidth });
        doc.y += 62;
      });

      // ══════════════════════════════════════════════════════════════════════
      // POST-PROCESS: add header/footer to every page except the cover
      // ══════════════════════════════════════════════════════════════════════
      const range = doc.bufferedPageRange();

      for (let i = 0; i < range.count; i++) {
        doc.switchToPage(range.start + i);
        doc.y = 0; // prevent post-process text() from triggering auto-page-add

        const pgNum = i + 1;

        // Skip cover page (page 1) — has its own dark design
        if (i === 0) continue;

        // Watermark
        if (watermark) {
          doc.save();
          doc.opacity(0.06);
          doc.fontSize(22).fillColor('#888888').font('Helvetica');
          for (let wy = 100; wy < pageHeight - 100; wy += 160) {
            doc.save();
            doc.rotate(32, { origin: [pageWidth / 2, wy] });
            doc.text(watermarkText, 0, wy, { width: pageWidth, align: 'center', lineBreak: false });
            doc.restore();
          }
          doc.restore();
        }

        // Header bar
        doc.rect(0, 0, pageWidth, 42).fill(accentHex);

        if (logoPath && fs.existsSync(logoPath)) {
          try { doc.image(logoPath, margin, 7, { height: 26, fit: [110, 26] }); } catch {
            doc.fontSize(13).fillColor('white').font('Helvetica-Bold')
              .text(hideFlacronBranding ? companyName : 'FlacronAI', margin, 14, { width: 200, lineBreak: false });
          }
        } else {
          doc.fontSize(13).fillColor('white').font('Helvetica-Bold')
            .text(hideFlacronBranding ? companyName : 'FlacronAI', margin, 14, { width: 200, lineBreak: false });
        }

        if (pgNum > 1) {
          doc.fontSize(9).fillColor('white').font('Helvetica')
            .text(`Claim: ${report.claimNumber || ''}`, pageWidth - 210, 16, { width: 160, align: 'right', lineBreak: false });
        }

        // Footer bar
        const fy = pageHeight - 32;
        doc.rect(0, fy, pageWidth, 32).fill('#f1f5f9');
        const footerLeft = reportFooter || (hideFlacronBranding ? companyName : 'FlacronAI — AI-Powered Insurance Reports');
        doc.fontSize(8).fillColor('#64748b').font('Helvetica')
          .text(footerLeft, margin, fy + 10, { width: contentWidth / 2, lineBreak: false });
        doc.text(`Page ${pgNum}`, margin + contentWidth / 2, fy + 10, { width: contentWidth / 2, align: 'right', lineBreak: false });
      }

      doc.flushPages();
      doc.end();

      stream.on('finish', () => resolve(outputPath));
      stream.on('error', reject);

    } catch (err) {
      reject(err);
    }
  });
};

module.exports = { generatePDF };
