import { motion } from 'framer-motion';
import Navbar from '../components/Navbar';
import Footer from '../components/Footer';

const SECTIONS = [
  {
    id: 'data-collection',
    title: '1. Data We Collect',
    content: `We collect information you provide directly and information generated by your use of the platform.

**Information you provide:**
- Account registration data: name, email address, and password (stored as a salted hash).
- Profile information: display name, phone number, company name, business address, and optional company logo.
- Claim data: claim numbers, insured names, property addresses, loss dates, loss types, and report types entered during report generation.
- Photos and files: damage photographs uploaded for AI analysis.
- Payment information: collected and processed exclusively by Stripe. We do not store credit card numbers.
- Communications: messages sent via our contact form, support tickets, or email.

**Information we collect automatically:**
- Usage data: pages visited, features used, reports generated, and timestamps.
- Device information: browser type, operating system, IP address, and session identifiers.
- Firebase Analytics data: aggregated and anonymized usage patterns to improve the service.`,
  },
  {
    id: 'how-we-use',
    title: '2. How We Use Your Data',
    content: `We use collected data for the following purposes:

- **Service delivery:** Generating AI-powered reports, processing exports, and maintaining your account.
- **Authentication and security:** Verifying your identity, detecting fraudulent activity, and protecting account security.
- **Payment processing:** Managing subscriptions, processing payments, and generating invoices through Stripe.
- **Customer support:** Responding to inquiries, resolving technical issues, and improving support quality.
- **Platform improvement:** Analyzing usage patterns to identify bugs, optimize performance, and develop new features.
- **Communications:** Sending transactional emails (report ready notifications, subscription updates) and, with consent, product announcements.
- **Legal compliance:** Meeting obligations under applicable law, including tax reporting and law enforcement requests with proper legal process.

We do not use your claim data, photos, or report content to train or improve AI models. Your insurance data remains your data.`,
  },
  {
    id: 'data-sharing',
    title: '3. Data Sharing',
    content: `We do not sell your personal data. We share data only as follows:

- **Service providers:** Third-party vendors who assist in delivering the service. This includes Google Firebase (authentication, database), Stripe (payments), OpenAI (AI processing), and IBM (WatsonX processing). All vendors are bound by data processing agreements and may not use your data for independent purposes.
- **OpenAI and IBM data handling:** Photos and claim text submitted for AI generation are transmitted to OpenAI and IBM WatsonX APIs for processing. Both companies process this data under strict confidentiality agreements and do not use submitted data for model training under our enterprise API terms.
- **Legal requirements:** We may disclose data when required by law, court order, or governmental authority, provided we have received proper legal process.
- **Business transfers:** In the event of a merger, acquisition, or sale of assets, customer data may be transferred as part of that transaction. We will provide notice before data is subject to a different privacy policy.
- **With your consent:** For any other purpose, only with your explicit consent.`,
  },
  {
    id: 'cookies',
    title: '4. Cookies and Tracking',
    content: `We use cookies and similar technologies to operate and improve the platform.

**Essential cookies:** Required for login sessions, security tokens, and core platform functionality. These cannot be disabled.

**Analytics cookies:** Used by Firebase Analytics to collect anonymized usage data. We use this information to understand feature adoption and improve the platform. You can opt out of Firebase Analytics through your browser's privacy controls or a browser extension.

**Preference cookies:** Stores your UI preferences (theme settings, dashboard configuration). These expire at the end of your browser session or after 30 days.

We do not use advertising cookies or share data with advertising networks. You can control cookie behavior through your browser settings. Disabling essential cookies will prevent platform login.`,
  },
  {
    id: 'data-retention',
    title: '5. Data Retention',
    content: `We retain your data for as long as your account is active and for a reasonable period thereafter.

- **Active accounts:** Data is retained for the full duration of your account's active status.
- **After account closure:** Account data is retained for 90 days after account closure to allow for recovery requests, then deleted from primary systems within 180 days. Backups may retain data for an additional 90 days.
- **Reports:** Generated reports are retained until explicitly deleted by you, or for 3 years if you do not delete them, subject to your plan's storage limits.
- **Photos:** Uploaded photos are stored for 90 days after report generation, then automatically purged unless explicitly saved.
- **Payment records:** Billing and invoice records are retained for 7 years to meet tax and legal obligations.
- **Deletion requests:** You may request immediate deletion of your account and associated data at any time. See Section 7 for your rights.`,
  },
  {
    id: 'security',
    title: '6. Security',
    content: `We take the security of your data seriously and implement industry-standard measures to protect it.

**Encryption:** All data is encrypted at rest using AES-256 encryption. All data in transit is protected using TLS 1.3 with certificate pinning on API endpoints.

**Infrastructure:** We use Google Cloud Platform (via Firebase) and MongoDB Atlas for data storage, both of which maintain SOC 2 Type II, ISO 27001, and GDPR-compliant certifications.

**Authentication:** User authentication is handled through Firebase Authentication, which implements industry-standard OAuth 2.0 and JWT token management. Passwords are never stored in plaintext.

**Access controls:** Data access within our systems is governed by the principle of least privilege. Employee access to customer data requires approval and is logged.

**Incident response:** In the event of a data breach affecting your personal data, we will notify affected users within 72 hours as required by GDPR Article 33, and as required by applicable US state laws.

While we implement robust security measures, no system is 100% secure. We encourage you to use a strong, unique password and to report any suspected security issues to support@flacronenterprises.com.`,
  },
  {
    id: 'your-rights',
    title: '7. Your Rights (GDPR & CCPA)',
    content: `Depending on your location, you may have the following rights regarding your personal data:

**For EU/EEA residents (GDPR):**
- Right of access: Request a copy of all personal data we hold about you.
- Right to rectification: Correct inaccurate or incomplete personal data.
- Right to erasure ("right to be forgotten"): Request deletion of your personal data, subject to legal retention requirements.
- Right to restriction of processing: Limit how we process your data in certain circumstances.
- Right to data portability: Receive your data in a machine-readable format.
- Right to object: Object to processing based on legitimate interests or for direct marketing.
- Right to withdraw consent: Withdraw consent at any time where processing is based on consent.

**For California residents (CCPA):**
- Right to know: Request disclosure of personal information collected, used, or shared.
- Right to delete: Request deletion of personal information.
- Right to opt out of sale: We do not sell personal information.
- Right to non-discrimination: We will not discriminate against you for exercising your privacy rights.

To exercise any of these rights, contact us at support@flacronenterprises.com with the subject "Privacy Request." We will respond within 30 days for GDPR requests and 45 days for CCPA requests. Identity verification may be required before processing certain requests.`,
  },
  {
    id: 'contact',
    title: '8. Contact Us',
    content: `If you have questions about this Privacy Policy, your data, or wish to exercise your rights, contact us at:

**FlacronAI, Inc.**
Email: support@flacronenterprises.com
Mailing Address: 410 E 95th St, Brooklyn, NY 11212, United States

For data protection inquiries from EU residents, you may also contact our Data Protection Representative by emailing support@flacronenterprises.com.

If you are not satisfied with our response, you have the right to lodge a complaint with your local data protection supervisory authority.`,
  },
];

export default function PrivacyPolicy() {
  return (
    <div className="min-h-screen bg-[#ffffff]">
      <Navbar />
      <div className="pt-24 pb-20 px-4 max-w-4xl mx-auto">
        <motion.div initial={{ opacity: 0, y: 30 }} animate={{ opacity: 1, y: 0 }}>
          <div className="mb-8">
            <h1 className="text-3xl font-bold text-gray-900 mb-2">Privacy Policy</h1>
            <p className="text-gray-600 text-sm">Last updated: March 1, 2026</p>
            <div className="mt-4 p-4 rounded-xl bg-orange-500/10 border border-orange-500/20">
              <p className="text-orange-300 text-sm">This Privacy Policy describes how FlacronAI, Inc. ("FlacronAI," "we," "our," or "us") collects, uses, and protects personal information when you use our platform at flacronai.com and related services.</p>
            </div>
          </div>

          <div className="flex gap-8">
            {/* TOC */}
            <aside className="hidden lg:block w-48 shrink-0">
              <nav className="sticky top-24 space-y-1">
                {SECTIONS.map(s => (
                  <a key={s.id} href={`#${s.id}`}
                    className="block text-xs text-gray-500 hover:text-orange-400 py-1.5 px-2 rounded-lg hover:bg-gray-100 transition-colors leading-snug">
                    {s.title}
                  </a>
                ))}
              </nav>
            </aside>

            {/* Content */}
            <div className="flex-1 space-y-8">
              {SECTIONS.map((section, i) => (
                <motion.div key={section.id} id={section.id} initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: i * 0.05 }}>
                  <h2 className="text-lg font-bold text-gray-900 mb-4 scroll-mt-24">{section.title}</h2>
                  <div className="prose-content text-gray-600 text-sm leading-relaxed">
                    {section.content.split('\n\n').map((para, pi) => {
                      if (para.startsWith('**') && !para.includes('\n')) {
                        return <p key={pi} className="font-semibold text-gray-900 mt-3 mb-1">{para.replace(/\*\*/g, '')}</p>;
                      }
                      const parts = para.split(/(\*\*[^*]+\*\*)/g);
                      return (
                        <p key={pi} className="mb-3">
                          {parts.map((p, ppi) => {
                            if (p.startsWith('**') && p.endsWith('**')) {
                              return <strong key={ppi} className="text-gray-900 font-semibold">{p.replace(/\*\*/g, '')}</strong>;
                            }
                            if (p.startsWith('- ')) {
                              return <span key={ppi} className="block ml-4">• {p.slice(2)}</span>;
                            }
                            return p;
                          })}
                        </p>
                      );
                    })}
                  </div>
                </motion.div>
              ))}
            </div>
          </div>
        </motion.div>
      </div>
      <Footer />
    </div>
  );
}
