import { useState, useEffect, useRef } from 'react';
import { motion } from 'framer-motion';
import { useNavigate } from 'react-router-dom';
import toast from 'react-hot-toast';
import {
  Palette, Globe, Upload, Eye, Download, Check, X, RefreshCw,
  Shield, Copy, ExternalLink, Monitor, Mail, FileText, Layout
} from 'lucide-react';
import Navbar from '../components/Navbar';
import { useAuth } from '../context/AuthContext';
import { whiteLabelAPI } from '../services/api';

const PREVIEW_MODES = [
  { id: 'report-header', label: 'Report Header', icon: FileText },
  { id: 'report-footer', label: 'Report Footer', icon: Layout },
  { id: 'email', label: 'Email Template', icon: Mail },
  { id: 'portal', label: 'Portal Header', icon: Monitor },
];

const WATERMARK_POSITIONS = ['Diagonal', 'Corner', 'None'];

const DEFAULT_CONFIG = {
  companyName: '',
  subdomain: '',
  primaryColor: '#f97316',
  secondaryColor: '#8b5cf6',
  logoUrl: '',
  headerText: '',
  footerText: '',
  reportFooter: '',
  emailFromName: '',
  emailFromAddress: '',
  hideFlacronBranding: false,
  watermarkText: '',
  watermarkOpacity: 30,
  watermarkPosition: 'Diagonal',
  customDomain: '',
};

function LivePreview({ config, mode }) {
  const style = { '--primary': config.primaryColor, '--secondary': config.secondaryColor };
  if (mode === 'report-header') return (
    <div className="bg-white rounded-xl p-6 text-gray-900 min-h-[300px]" style={style}>
      <div className="flex items-center justify-between border-b-2 pb-4 mb-4" style={{ borderColor: config.primaryColor }}>
        <div className="flex items-center gap-3">
          {config.logoUrl
            ? <img src={config.logoUrl} alt="logo" className="h-12 object-contain" />
            : <div className="w-12 h-12 rounded-lg flex items-center justify-center text-gray-900 font-bold text-lg" style={{ background: config.primaryColor }}>
                {(config.companyName || 'A')[0]}
              </div>}
          <div>
            <p className="font-bold text-lg" style={{ color: config.primaryColor }}>{config.companyName || 'Your Company Name'}</p>
            <p className="text-sm text-gray-500">{config.headerText || 'Insurance Claim Report'}</p>
          </div>
        </div>
        <div className="text-right text-xs text-gray-500">
          <p>Report Date: {new Date().toLocaleDateString()}</p>
          <p>Ref: CLM-2024-001</p>
        </div>
      </div>
      <div className="relative">
        {config.watermarkPosition !== 'None' && config.watermarkText && (
          <div className="absolute inset-0 flex items-center justify-center pointer-events-none overflow-hidden">
            <span className={`text-4xl font-bold text-gray-200 select-none ${config.watermarkPosition === 'Diagonal' ? '-rotate-45' : ''}`}
              style={{ opacity: config.watermarkOpacity / 100 }}>
              {config.watermarkText}
            </span>
          </div>
        )}
        <div className="space-y-2">
          <div className="h-3 bg-gray-200 rounded w-3/4" />
          <div className="h-3 bg-gray-200 rounded w-full" />
          <div className="h-3 bg-gray-200 rounded w-5/6" />
          <div className="h-3 bg-gray-200 rounded w-2/3" />
        </div>
      </div>
    </div>
  );

  if (mode === 'report-footer') return (
    <div className="bg-white rounded-xl p-6 text-gray-900 min-h-[300px]" style={style}>
      <div className="mt-auto border-t pt-4" style={{ borderColor: config.primaryColor }}>
        <div className="flex justify-between items-end">
          <div>
            <p className="text-xs text-gray-500">{config.footerText || 'Generated by ' + (config.companyName || 'Your Company')}</p>
            <p className="text-xs text-gray-600 mt-1">{config.reportFooter || 'All rights reserved.'}</p>
            {!config.hideFlacronBranding && <p className="text-xs text-gray-700 mt-1">Powered by FlacronAI</p>}
          </div>
          <div className="text-right text-xs text-gray-600">
            <p>Page 1 of 1</p>
          </div>
        </div>
      </div>
    </div>
  );

  if (mode === 'email') return (
    <div className="bg-gray-100 rounded-xl p-4 min-h-[300px]">
      <div className="bg-white rounded-lg overflow-hidden shadow">
        <div className="p-4 text-gray-900" style={{ background: config.primaryColor }}>
          <p className="font-bold">{config.emailFromName || config.companyName || 'Your Company'}</p>
          <p className="text-xs opacity-80">no-reply@{config.subdomain || 'yourdomain'}.flacronai.com</p>
        </div>
        <div className="p-5">
          <h3 className="font-bold text-gray-800 mb-2">Your Report is Ready</h3>
          <p className="text-sm text-gray-600 mb-4">Your insurance claim report for CLM-2024-001 has been generated and is ready to download.</p>
          <button className="text-gray-900 px-4 py-2 rounded-lg text-sm font-semibold" style={{ background: config.primaryColor }}>
            Download Report
          </button>
          <p className="text-xs text-gray-600 mt-4">{config.footerText || `© ${new Date().getFullYear()} ${config.companyName || 'Your Company'}`}</p>
        </div>
      </div>
    </div>
  );

  if (mode === 'portal') return (
    <div className="bg-[#ffffff] rounded-xl overflow-hidden min-h-[300px]">
      <nav className="flex items-center justify-between px-6 py-4 border-b border-gray-200" style={{ background: config.primaryColor + '20' }}>
        <div className="flex items-center gap-3">
          {config.logoUrl
            ? <img src={config.logoUrl} alt="logo" className="h-8 object-contain" />
            : <div className="w-8 h-8 rounded-lg flex items-center justify-center text-gray-900 text-sm font-bold" style={{ background: config.primaryColor }}>
                {(config.companyName || 'A')[0]}
              </div>}
          <span className="text-gray-900 font-semibold">{config.companyName || 'Your Company'}</span>
        </div>
        <div className="flex gap-4 text-sm text-gray-600">
          <span>Dashboard</span><span>Reports</span><span>Settings</span>
        </div>
      </nav>
      <div className="p-6">
        <h2 className="text-gray-900 text-lg font-bold mb-2">Welcome back</h2>
        <p className="text-gray-600 text-sm">Manage your claims and reports from your {config.companyName || 'company'} portal.</p>
        <div className="mt-4 flex gap-3">
          <div className="h-20 flex-1 rounded-xl border border-gray-200" style={{ background: config.primaryColor + '15' }} />
          <div className="h-20 flex-1 rounded-xl border border-gray-200 bg-gray-100" />
          <div className="h-20 flex-1 rounded-xl border border-gray-200 bg-gray-100" />
        </div>
      </div>
    </div>
  );

  return null;
}

export default function WhiteLabelPortal() {
  const { tier } = useAuth();
  const navigate = useNavigate();
  const logoInputRef = useRef();
  const [config, setConfig] = useState(DEFAULT_CONFIG);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [previewMode, setPreviewMode] = useState('report-header');
  const [verifyingDomain, setVerifyingDomain] = useState(false);
  const [domainStatus, setDomainStatus] = useState(null);
  const [logoUploading, setLogoUploading] = useState(false);
  const [previewDownloading, setPreviewDownloading] = useState(false);
  const [cnamecopied, setCnameCopied] = useState(false);

  useEffect(() => {
    whiteLabelAPI.getConfig().then(res => {
      setConfig({ ...DEFAULT_CONFIG, ...(res.data?.config || res.data || {}) });
    }).catch(() => {}).finally(() => setLoading(false));
  }, []);

  const handleSave = async () => {
    setSaving(true);
    try {
      await whiteLabelAPI.updateConfig(config);
      toast.success('White-label configuration saved');
    } catch { toast.error('Failed to save configuration'); }
    finally { setSaving(false); }
  };

  const handleLogoUpload = async (e) => {
    const file = e.target.files?.[0]; if (!file) return;
    if (file.size > 2 * 1024 * 1024) { toast.error('Logo must be under 2MB'); return; }
    setLogoUploading(true);
    try {
      const fd = new FormData(); fd.append('logo', file);
      const res = await whiteLabelAPI.uploadLogo(fd);
      setConfig(p => ({ ...p, logoUrl: res.data.url || res.data.logoUrl }));
      toast.success('Logo uploaded');
    } catch { toast.error('Logo upload failed'); }
    finally { setLogoUploading(false); e.target.value = ''; }
  };

  const handlePreviewPDF = async () => {
    setPreviewDownloading(true);
    try {
      const res = await whiteLabelAPI.preview();
      const url = URL.createObjectURL(res.data);
      const a = document.createElement('a'); a.href = url; a.download = 'preview-report.pdf'; a.click();
      toast.success('Preview PDF downloaded');
    } catch { toast.error('Preview generation failed'); }
    finally { setPreviewDownloading(false); }
  };

  const handleVerifyDomain = async () => {
    if (!config.customDomain) { toast.error('Enter a domain first'); return; }
    setVerifyingDomain(true);
    try {
      const res = await whiteLabelAPI.updateConfig({ customDomain: config.customDomain, verifyDomain: true });
      setDomainStatus(res.data?.domainStatus || 'pending');
      toast.success('Domain verification initiated');
    } catch { toast.error('Verification failed'); setDomainStatus('error'); }
    finally { setVerifyingDomain(false); }
  };

  const cnamValue = `${config.subdomain || 'yoursubdomain'}.flacronai.com`;

  if (tier !== 'enterprise') {
    return (
      <div className="min-h-screen bg-[#ffffff]">
        <Navbar />
        <div className="pt-24 flex items-center justify-center">
          <div className="card p-10 max-w-md text-center">
            <Palette className="w-12 h-12 text-gray-600 mx-auto mb-4" />
            <h2 className="text-xl font-bold text-gray-900 mb-2">Enterprise Only Feature</h2>
            <p className="text-gray-600 text-sm mb-6">White-label portal configuration is available exclusively for Enterprise plan customers.</p>
            <button onClick={() => navigate('/pricing')} className="btn-primary">View Enterprise Plan</button>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-[#ffffff]">
      <Navbar />
      <div className="pt-24 pb-16 px-4 max-w-7xl mx-auto">
        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="mb-8">
          <h1 className="text-2xl font-bold text-gray-900">White-Label Portal</h1>
          <p className="text-gray-600 text-sm mt-1">Customize your branded client portal and reports</p>
        </motion.div>

        {loading ? (
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
            {[...Array(6)].map((_, i) => <div key={i} className="skeleton h-40 rounded-2xl" />)}
          </div>
        ) : (
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
            {/* Left: Settings */}
            <div className="space-y-5">
              {/* Branding */}
              <div className="card p-6">
                <h2 className="text-base font-semibold text-gray-900 mb-4 flex items-center gap-2"><Palette className="w-4 h-4" /> Branding</h2>
                <div className="space-y-4">
                  <div>
                    <label className="label">Company Name</label>
                    <input className="input" placeholder="Your Company Inc." value={config.companyName} onChange={e => setConfig(p => ({ ...p, companyName: e.target.value }))} />
                  </div>
                  <div>
                    <label className="label">Subdomain</label>
                    <div className="flex items-center gap-2">
                      <input className="input flex-1" placeholder="yourcompany" value={config.subdomain} onChange={e => setConfig(p => ({ ...p, subdomain: e.target.value.toLowerCase().replace(/[^a-z0-9-]/g, '') }))} />
                    </div>
                    {config.subdomain && (
                      <p className="text-xs text-orange-400 mt-1">Preview URL: <span className="font-mono">{config.subdomain}.flacronai.com</span></p>
                    )}
                  </div>
                  <div className="grid grid-cols-2 gap-4">
                    <div>
                      <label className="label">Primary Color</label>
                      <div className="flex gap-2">
                        <input type="color" className="h-10 w-14 rounded-lg border border-gray-200 bg-transparent cursor-pointer" value={config.primaryColor} onChange={e => setConfig(p => ({ ...p, primaryColor: e.target.value }))} />
                        <input className="input flex-1 font-mono" value={config.primaryColor} onChange={e => setConfig(p => ({ ...p, primaryColor: e.target.value }))} />
                      </div>
                    </div>
                    <div>
                      <label className="label">Secondary Color</label>
                      <div className="flex gap-2">
                        <input type="color" className="h-10 w-14 rounded-lg border border-gray-200 bg-transparent cursor-pointer" value={config.secondaryColor} onChange={e => setConfig(p => ({ ...p, secondaryColor: e.target.value }))} />
                        <input className="input flex-1 font-mono" value={config.secondaryColor} onChange={e => setConfig(p => ({ ...p, secondaryColor: e.target.value }))} />
                      </div>
                    </div>
                  </div>
                  <div>
                    <label className="label">Company Logo</label>
                    <div className="flex items-center gap-3">
                      {config.logoUrl && <img src={config.logoUrl} alt="logo" className="h-10 object-contain rounded-lg" />}
                      <button onClick={() => logoInputRef.current?.click()} disabled={logoUploading} className="btn-secondary text-sm py-2 flex items-center gap-2">
                        <Upload className="w-4 h-4" /> {logoUploading ? 'Uploading...' : 'Upload Logo'}
                      </button>
                      <input ref={logoInputRef} type="file" accept="image/*" className="hidden" onChange={handleLogoUpload} />
                    </div>
                  </div>
                  <div>
                    <label className="label">Header Text</label>
                    <input className="input" placeholder="Insurance Claim Reports" value={config.headerText} onChange={e => setConfig(p => ({ ...p, headerText: e.target.value }))} />
                  </div>
                  <div>
                    <label className="label">Footer Text</label>
                    <input className="input" placeholder="© 2024 Your Company. All rights reserved." value={config.footerText} onChange={e => setConfig(p => ({ ...p, footerText: e.target.value }))} />
                  </div>
                  <div>
                    <label className="label">Custom Report Footer</label>
                    <textarea className="input min-h-[70px]" placeholder="Additional footer text for reports..." value={config.reportFooter} onChange={e => setConfig(p => ({ ...p, reportFooter: e.target.value }))} />
                  </div>
                  <div className="grid grid-cols-2 gap-4">
                    <div>
                      <label className="label">Email From Name</label>
                      <input className="input" placeholder="Your Company Reports" value={config.emailFromName} onChange={e => setConfig(p => ({ ...p, emailFromName: e.target.value }))} />
                    </div>
                    <div>
                      <label className="label">Email From Address</label>
                      <input type="email" className="input" placeholder="reports@yourcompany.com" value={config.emailFromAddress} onChange={e => setConfig(p => ({ ...p, emailFromAddress: e.target.value }))} />
                    </div>
                  </div>
                  <label className="flex items-center gap-3 cursor-pointer">
                    <input type="checkbox" checked={config.hideFlacronBranding} onChange={e => setConfig(p => ({ ...p, hideFlacronBranding: e.target.checked }))} />
                    <span className="text-sm text-gray-700">Hide "Powered by FlacronAI" branding</span>
                  </label>
                </div>
              </div>

              {/* Watermark */}
              <div className="card p-6">
                <h2 className="text-base font-semibold text-gray-900 mb-4 flex items-center gap-2"><Eye className="w-4 h-4" /> Watermark Settings</h2>
                <div className="space-y-4">
                  <div>
                    <label className="label">Watermark Text</label>
                    <input className="input" placeholder="e.g. CONFIDENTIAL or your company name" value={config.watermarkText} onChange={e => setConfig(p => ({ ...p, watermarkText: e.target.value }))} />
                  </div>
                  <div>
                    <label className="label">Opacity ({config.watermarkOpacity}%)</label>
                    <input type="range" min={5} max={60} value={config.watermarkOpacity} onChange={e => setConfig(p => ({ ...p, watermarkOpacity: Number(e.target.value) }))}
                      className="w-full h-2 bg-gray-100 rounded-lg appearance-none cursor-pointer accent-orange-500" />
                  </div>
                  <div>
                    <label className="label">Position</label>
                    <select className="input" value={config.watermarkPosition} onChange={e => setConfig(p => ({ ...p, watermarkPosition: e.target.value }))}>
                      {WATERMARK_POSITIONS.map(p => <option key={p}>{p}</option>)}
                    </select>
                  </div>
                </div>
              </div>

              {/* Custom Domain */}
              <div className="card p-6">
                <h2 className="text-base font-semibold text-gray-900 mb-4 flex items-center gap-2"><Globe className="w-4 h-4" /> Custom Domain</h2>
                <div className="p-4 rounded-xl bg-orange-500/10 border border-orange-500/20 mb-4">
                  <p className="text-blue-300 text-sm font-medium mb-2">CNAME Setup Instructions</p>
                  <p className="text-blue-200 text-xs mb-2">Add this CNAME record to your DNS provider:</p>
                  <div className="flex items-center gap-2 bg-black/30 rounded-lg p-2">
                    <code className="text-xs font-mono text-green-300 flex-1 break-all">{cnamValue}</code>
                    <button onClick={() => { navigator.clipboard.writeText(cnamValue); setCnameCopied(true); setTimeout(() => setCnameCopied(false), 2000); }}
                      className="p-1 hover:bg-gray-100 rounded">
                      {cnamecopied ? <Check className="w-3 h-3 text-green-400" /> : <Copy className="w-3 h-3 text-gray-600" />}
                    </button>
                  </div>
                </div>
                <div className="space-y-3">
                  <div>
                    <label className="label">Your Domain</label>
                    <input className="input" placeholder="reports.yourcompany.com" value={config.customDomain} onChange={e => setConfig(p => ({ ...p, customDomain: e.target.value }))} />
                  </div>
                  <div className="flex gap-3">
                    <button onClick={handleVerifyDomain} disabled={verifyingDomain} className="btn-secondary text-sm py-2 px-4 flex items-center gap-2 disabled:opacity-50">
                      {verifyingDomain ? <RefreshCw className="w-4 h-4 animate-spin" /> : <Shield className="w-4 h-4" />}
                      {verifyingDomain ? 'Verifying...' : 'Verify Domain'}
                    </button>
                    {domainStatus && (
                      <div className={`flex items-center gap-2 text-sm px-3 py-2 rounded-xl border ${
                        domainStatus === 'active' ? 'bg-green-500/10 border-green-500/20 text-green-400' :
                        domainStatus === 'error' ? 'bg-red-500/10 border-red-500/20 text-red-400' :
                        'bg-yellow-500/10 border-yellow-500/20 text-yellow-400'}`}>
                        {domainStatus === 'active' ? <Check className="w-4 h-4" /> : <RefreshCw className="w-4 h-4" />}
                        {domainStatus === 'active' ? 'Verified + SSL Active' : domainStatus === 'error' ? 'Verification Failed' : 'Pending (DNS propagation)'}
                      </div>
                    )}
                  </div>
                </div>
              </div>

              {/* Action Buttons */}
              <div className="flex gap-3">
                <button onClick={handleSave} disabled={saving} className="btn-primary flex items-center gap-2 disabled:opacity-50">
                  {saving ? <RefreshCw className="w-4 h-4 animate-spin" /> : <Check className="w-4 h-4" />}
                  {saving ? 'Saving...' : 'Apply Changes'}
                </button>
                <button onClick={handlePreviewPDF} disabled={previewDownloading} className="btn-secondary flex items-center gap-2 disabled:opacity-50">
                  {previewDownloading ? <RefreshCw className="w-4 h-4 animate-spin" /> : <Download className="w-4 h-4" />}
                  Preview PDF
                </button>
              </div>
            </div>

            {/* Right: Live Preview */}
            <div className="space-y-4">
              <div className="card p-5 sticky top-24">
                <div className="flex items-center justify-between mb-4">
                  <h2 className="text-base font-semibold text-gray-900">Live Preview</h2>
                  <div className="flex flex-wrap gap-1">
                    {PREVIEW_MODES.map(m => (
                      <button key={m.id} onClick={() => setPreviewMode(m.id)}
                        className={`px-2.5 py-1.5 rounded-lg text-xs font-medium flex items-center gap-1.5 transition-colors ${
                          previewMode === m.id ? 'bg-orange-500 text-gray-900' : 'bg-gray-100 text-gray-600 hover:text-gray-900'}`}>
                        <m.icon className="w-3 h-3" /> {m.label}
                      </button>
                    ))}
                  </div>
                </div>
                <LivePreview config={config} mode={previewMode} />
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
